# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
