# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181025_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
